version: "3"

services:
  postgres:
    container_name: postgres
    ports:
      - 5432:5432
    image: postgres:alpine
    environment:
      - POSTGRES_USER=turboAf
      - POSTGRES_PASSWORD=getTurbo
      - POSTGRES_DB=prisma
    restart: always

  api:
    container_name: api
    ports:
      - 5000:5000
    build:
      context: ./apps/api
      dockerfile: Dockerfile

  web:
    container_name: web
    ports:
      - 3000:3000
    build:
      context: ./apps/web
      dockerfile: Dockerfile
