FROM node:16-slim

RUN apt-get update
RUN apt-get install -y openssl

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json .
RUN npm install

# Copying source files
COPY . .

# Exports
EXPOSE 5000
CMD ["node", "index.js"]