FROM node:alpine3.11

WORKDIR /app/frontend

# To use packages in CLI without global install
ENV PATH /app/frontend/node_modules/.bin:$PATH

COPY . .

RUN npm install --silent

ENV GIT_WORK_TREE=/app/frontend GIT_DIR=/app/.git

RUN apk update && \
    apk add git

CMD ["/bin/sh", "-c", "jest --watch"]