FROM node:16-alpine3.14

ENV PORT 3000

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json .
RUN npm install

# Copying source files
COPY . .

# Build the app
RUN npm run build
EXPOSE 3000

# Run in dev mode
CMD [ "npm", "run", "dev" ]